Repository appuio/component-openshift4-terraform, pull requests merged in 2021-11, with the labels that each got.

#29 Allow passing team for alerting
  class/defaults.yml
  component/main.jsonnet
Labels: enhancement

#30 Bump exoscale module to v1.4.2
  class/defaults.yml
Labels: dependency

#31 Bump cloudscale module version
  class/defaults.yml
Labels: change
