Repository appuio/component-openshift4-terraform, pull requests merged in 2021-07, with the labels that each got.

#10 Custom Terraform scripts
  class/defaults.yml
  class/openshift4-terraform.yml
  component/gitlab-ci.jsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/how-tos/use-exoscale.adoc
  scripts/git-askpass.sh
  scripts/terraform.sh
  scripts/tf.sh
  tests/exoscale.yaml
Labels: enhancement

#13 Pin default version to v1.0.0
  class/defaults.yml
  tests/cloudscale.yaml
  tests/exoscale.yaml
Labels: change

#12 Add support for puppet-managed LBs on cloudscale
  .github/workflows/release.yaml
  class/defaults.yml
  component/gitlab-ci.jsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/how-tos/upgrade-cloudscale-v1-v2.adoc
  docs/modules/ROOT/pages/how-tos/use-cloudscale.adoc
  docs/modules/ROOT/pages/how-tos/use-exoscale.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/partials/nav.adoc
  docs/modules/ROOT/partials/puppet-lb-cred.adoc
  tests/cloudscale.yaml
Labels: breaking

#14 Suppress output of `apk add` in terraform wrapper script
  scripts/terraform.sh
Labels: bug

#15 Add how-to for migrating from openshift4-cloudscale
  docs/modules/ROOT/pages/how-tos/migrate-from-openshift4-cloudscale.adoc
  docs/modules/ROOT/pages/how-tos/upgrade-cloudscale-v1-v2.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#16 Bump cloudscale.ch Terraform module default version to v2.0.1
  class/defaults.yml
Labels: dependency

#17 Update component parameter documentation
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: documentation
