Repository appuio/component-openshift4-terraform, pull requests merged in 2022-10, with the labels that each got.

#62 Bump Terraform to 1.3.1
  class/defaults.yml
Labels: breaking

#63 Update component to latest component template version
  .cruft.json
  .editorconfig
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/lint.yaml
  .github/workflows/test.yaml
  .gitignore
  .yamllint.yml
  Makefile
  Makefile.vars.mk
  README.md
  docs/modules/ROOT/pages/how-tos/.gitkeep
  renovate.json
  tests/cloudscale.yml
  tests/exoscale.yml
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/.gitignore
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/backend.tf.json
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/git-askpass.sh
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/gitlab-ci.yml
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/main.tf.json
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/migrate-state-exoscale-v3-v4.sh
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/migrate-state-v2-v3.sh
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/outputs.tf.json
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/terraform.sh
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/tf.sh
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/variables.tf.json
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/.gitignore
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/backend.tf.json
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/git-askpass.sh
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/gitlab-ci.yml
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/main.tf.json
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/migrate-state-exoscale-v3-v4.sh
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/migrate-state-v2-v3.sh
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/outputs.tf.json
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/terraform.sh
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/tf.sh
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/variables.tf.json
Labels: ignore

#64 Make unsupported Terraform module versions a compilation error
  component/main.jsonnet
  docs/modules/ROOT/pages/index.adoc
Labels: breaking

#65 Add step to update compute instance types in Exoscale migration howto for v4 to v5
  docs/modules/ROOT/pages/how-tos/upgrade-exoscale-v4-v5.adoc
Labels: documentation

#66 Fix formatting in Exoscale v4 to v5 upgrade how-to
  docs/modules/ROOT/pages/how-tos/upgrade-exoscale-v4-v5.adoc
Labels: ignore

#67 Update dependency registry.gitlab.com/gitlab-org/terraform-images/releases/terraform to v1.3.2
  class/defaults.yml
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/gitlab-ci.yml
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/gitlab-ci.yml
Labels: dependency

#68 Update dependency registry.gitlab.com/gitlab-org/terraform-images/releases/terraform to v1.3.3
  class/defaults.yml
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/gitlab-ci.yml
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/gitlab-ci.yml
Labels: dependency

#69 Update Exoscale terraform module to v3.1.0
  class/defaults.yml
  docs/modules/ROOT/pages/how-tos/upgrade-exoscale-v4-v5.adoc
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/main.tf.json
Labels: dependency
