Repository appuio/component-openshift4-terraform, pull requests merged in 2023-07, with the labels that each got.

#81 Switch back to user-provided Floaty IAM Key on Exoscale
  class/defaults.yml
  component/gitlab-ci.jsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/how-tos/use-exoscale.adoc
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/gitlab-ci.yml
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/main.tf.json
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/variables.tf.json
Labels: breaking

#82 Update from template
  .cruft.json
  .editorconfig
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release.yaml
  Makefile.vars.mk
  docs/modules/ROOT/pages/.vale.ini
Labels: template-sync

#78 Update registry.gitlab.com/gitlab-org/terraform-images/releases/terraform Docker tag to v1.5.1
  class/defaults.yml
  tests/golden/cloudscale/openshift4-terraform/openshift4-terraform/gitlab-ci.yml
  tests/golden/exoscale/openshift4-terraform/openshift4-terraform/gitlab-ci.yml
Labels: dependency
